//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookEvent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Create_Event_
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Location { get; set; }
        public Nullable<System.TimeSpan> Start_Time { get; set; }
        public string Type_public_private_ { get; set; }
        public int Duration_in_hours { get; set; }
        public string Description { get; set; }
        public string Other_Deatils { get; set; }
        public string Invite_by_Email { get; set; }
    }
}
