//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookEvent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Register
    {
        public int Id { get; set; }
        public string Full_Name { get; set; }
        public string E_mail { get; set; }
        public string Password { get; set; }
    }
}
